version: 3

tasks:

  default:
    silent: true
    cmd: task --list --color

  ruff:
    cmd: rye run ruff format src

  sort:
    cmd: rye run usort format src

  fmt:
    deps: [ ruff, sort ]

  revision:
    cmd: rye run alembic revision --autogenerate

  upgrade:
    cmd: rye run alembic upgrade head

  mgrt:
    deps: [ revision, upgrade ]