"""empty message

Revision ID: b4d680a6375b
Revises:
Create Date: 2024-08-18 14:20:11.867237

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b4d680a6375b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "puzzles",
        sa.Column("puzzle_id", sa.Integer(), nullable=False),
        sa.Column("size", sa.SmallInteger(), nullable=False),
        sa.Column("score", sa.SmallInteger(), nullable=False),
        sa.Column("complexity", sa.String(length=10), nullable=False),
        sa.Column(
            "sample",
            postgresql.ARRAY(sa.SmallInteger(), dimensions=1, zero_indexes=True),
            nullable=False,
        ),
        sa.Column(
            "original",
            postgresql.ARRAY(sa.SmallInteger(), dimensions=1, zero_indexes=True),
            nullable=False,
        ),
        sa.Column(
            "zeroed",
            postgresql.ARRAY(sa.SmallInteger(), dimensions=1, zero_indexes=True),
            nullable=False,
        ),
        sa.Column(
            "modified",
            postgresql.ARRAY(sa.SmallInteger(), dimensions=1, zero_indexes=True),
            nullable=False,
        ),
        sa.Column(
            "vertical",
            postgresql.ARRAY(sa.SmallInteger(), dimensions=1, zero_indexes=True),
            nullable=False,
        ),
        sa.Column(
            "horizontal",
            postgresql.ARRAY(sa.SmallInteger(), dimensions=1, zero_indexes=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("puzzle_id", name=op.f("pk_puzzles")),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("user_name", sa.String(length=32), nullable=True),
        sa.Column("locale", sa.String(length=2), nullable=False),
        sa.Column("anncmt", sa.String(length=5), nullable=False),
        sa.Column("style", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_users")),
    )
    op.create_table(
        "ranking",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.user_id"], name=op.f("fk_ranking_user_id_users")
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_ranking")),
    )
    op.create_table(
        "solved",
        sa.Column("solve_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("puzzle_id", sa.Integer(), nullable=False),
        sa.Column("size", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.user_id"], name=op.f("fk_solved_user_id_users")
        ),
        sa.PrimaryKeyConstraint("solve_id", name=op.f("pk_solved")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("solved")
    op.drop_table("ranking")
    op.drop_table("users")
    op.drop_table("puzzles")
    # ### end Alembic commands ###
