[development.app]
level = 'debug'

[development.bot]
storage = 'redis'

[development.database]
host = 'localhost'
port = 5432
username = 'postgres'
password = 'postgres'
database = 'postgres'
driver = 'postgresql+asyncpg'

[development.redis]
host = 'localhost'
port = 6379
database = 1
database_fsm = 0