[development.common]
level = 'debug'

[development.database]
host = 'localhost'
port = 5432
username = 'postgres'
password = 'postgres'
database = 'postgres'
driver = 'postgresql+psycopg'

[development.redis]
host = 'localhost'
port = 6379
database = 1

[development.nats]
host = 'localhost'
port = 4222
