"""empty message

Revision ID: 370fbe677c4a
Revises:
Create Date: 2024-08-10 16:45:19.235265

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "370fbe677c4a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "puzzles",
        sa.Column("puzzle_id", sa.Integer(), nullable=False),
        sa.Column("size", sa.SmallInteger(), nullable=False),
        sa.Column("score", sa.SmallInteger(), nullable=False),
        sa.Column("complexity", sa.String(length=10), nullable=False),
        sa.Column(
            "index_sample",
            postgresql.ARRAY(sa.SmallInteger(), dimensions=1, zero_indexes=True),
            nullable=False,
        ),
        sa.Column(
            "original_array",
            postgresql.ARRAY(sa.SmallInteger(), dimensions=1, zero_indexes=True),
            nullable=False,
        ),
        sa.Column(
            "zeroed_array",
            postgresql.ARRAY(sa.SmallInteger(), dimensions=1, zero_indexes=True),
            nullable=False,
        ),
        sa.Column(
            "modified_array",
            postgresql.ARRAY(sa.SmallInteger(), dimensions=1, zero_indexes=True),
            nullable=False,
        ),
        sa.Column(
            "vertical_sums",
            postgresql.ARRAY(sa.SmallInteger(), dimensions=1, zero_indexes=True),
            nullable=False,
        ),
        sa.Column(
            "horizontal_sums",
            postgresql.ARRAY(sa.SmallInteger(), dimensions=1, zero_indexes=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("puzzle_id", name=op.f("pk_puzzles")),
    )
    op.create_table(
        "users",
        sa.Column("tg_id", sa.BigInteger(), nullable=False),
        sa.Column("first_name", sa.String(length=32), nullable=False),
        sa.Column("last_name", sa.String(length=64), nullable=False),
        sa.Column("username", sa.String(length=32), nullable=False),
        sa.Column("language", sa.String(length=5), nullable=False),
        sa.Column("notify", sa.Boolean(), nullable=False),
        sa.Column("style", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("tg_id", name=op.f("pk_users")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("puzzles")
    # ### end Alembic commands ###
