"""first

Revision ID: 927afc6c370e
Revises: 
Create Date: 2024-08-08 12:36:24.565159

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "927afc6c370e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "puzzles",
        sa.Column("puzzle_id", sa.Integer(), nullable=False),
        sa.Column("size", sa.SmallInteger(), nullable=False),
        sa.Column(
            "original",
            postgresql.ARRAY(sa.SmallInteger(), dimensions=2),
            nullable=False,
        ),
        sa.Column(
            "modified",
            postgresql.ARRAY(sa.SmallInteger(), dimensions=2),
            nullable=False,
        ),
        sa.Column(
            "sums", postgresql.ARRAY(sa.SmallInteger(), dimensions=2), nullable=False
        ),
        sa.PrimaryKeyConstraint("puzzle_id", name=op.f("pk_puzzles")),
    )
    op.create_table(
        "users",
        sa.Column("tg_id", sa.BigInteger(), nullable=False),
        sa.Column("first_name", sa.String(length=32), nullable=False),
        sa.Column("last_name", sa.String(length=64), nullable=False),
        sa.Column("username", sa.String(length=32), nullable=False),
        sa.Column("language", sa.String(length=5), nullable=False),
        sa.Column("notify", sa.Boolean(), nullable=False),
        sa.Column("style", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("tg_id", name=op.f("pk_users")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("puzzles")
    # ### end Alembic commands ###
